name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install Conan
        run: pip install conan
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -G "Visual Studio 17 2022" -B build
      - name: Build
        run: cmake --build build --config Release
